version: '3.8'

services:
  gumaspending:
    build: .
    container_name: gumaspending_app
    restart: unless-stopped
    ports:
      - "8060:8060"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8060
    env_file:
      - .env
    volumes:
      - .:/app
