version: '3.8'

services:
  gumatube:
    build: .
    container_name: gumatube_app
    ports:
      - "8083:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./output:/app/output
      - ./yt-dlp-cache:/root/.cache/yt-dlp
      - ./huggingface-cache:/root/.cache/huggingface
    environment:
      - FLASK_ENV=development
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=""
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - gumatube_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: gumatube_qdrant
    ports:
      - "6334:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - gumatube_network

networks:
  gumatube_network:
    driver: bridge
