version: "3.8"

services:
  gumatutordoc:
    build: .
    container_name: gumatutordoc_app
    ports:
      - "8084:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./outputs/html:/app/outputs/html
    env_file:
      - ../.env
    restart: unless-stopped
