version: '3.8'

services:
  gumaphoto:
    build: .
    container_name: gumaphoto_app
    ports:
      - "8085:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - D:/Pictures/uploads_raw:/app/data/uploads_raw
      - D:/Pictures:/app/data/organized
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ../.env
    depends_on:
      - qdrant
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - gumaphoto_network

  celery_worker:
    build: .
    container_name: gumaphoto_celery
    command: ["/usr/local/bin/celery", "-A", "core.celery_app", "worker", "-B", "--loglevel=info", "--concurrency=1"]
    volumes:
      - .:/app
      - ./data:/app/data
      - D:/Pictures/uploads_raw:/app/data/uploads_raw
      - D:/Pictures:/app/data/organized
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ../.env
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - gumaphoto_network

  redis:
    image: redis:alpine
    container_name: gumaphoto_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - gumaphoto_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: gumaphoto_qdrant
    ports:
      - "6337:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - gumaphoto_network

networks:
  gumaphoto_network:
    driver: bridge
